### ISSUE TITLE
Generate YAML templates during installation

### ISSUE THREAD

**Issue by yousefmoazzam** [DiamondLightSource/httomo#300]
The YAML checker depends on the YAML templates existing in order to perform the checks that the methods specified in a pipeline are valid methods in the associated packages: https://github.com/DiamondLightSource/httomo/blob/f53709ac6350898dcfe874961241d98e3a722f84/httomo/yaml_checker.py#L130-L146

Thus, it would make sense to generate the YAML templates during installation of httomo, so then the YAML checker is ready to use after installation.

**Comment by yousefmoazzam** [comment]
A few comments:
- if it's difficult to do this with `pyproject.toml` alone, _and_ poetry plays nicely with conda, then using poetry would be ok
- if it's doable without poetry, that would be nice, since it would be another thing to deal with for packaging
- I've not heard this notion before of generating files for an installation during test execution, does this involve running `pytest` during the `pip install`/`conda install` somehow?  (I do recall there being the ability to run tests during `conda build`, but that's all I remember). What are the benefits of having the YAML template generation wrapped within tests, is it a means of detecting failure of the YAML templates generation?

**Comment by yousefmoazzam** [comment]
Yeahhh, this is looks quite tricky to accomplish...

With some fiddling, it was possible to provide a custom step in the build process that occurs during a `pip install` to run the YAML templates generator script for the various backends in the `generate-yaml-templates` branch https://github.com/DiamondLightSource/httomo/blob/38f3ac81ef01126243cccfe7c763ceb0cf71d72c/setup.py

This does indeed manage to generate the `yaml_templates/` dir in the `build/` dir that eventually has its contents copied to the installation destination by `pip install`

However, when it gets to calling the function in `yaml_templates_generator.py`, the issue is that it needs to import the various backend packages in order to inspect the signatures of the functions... The backends aren't installed in the build environment that `pip` creates, and thus the YAML templates generation fails at this point:
```
Traceback (most recent call last):
    File "/dls/science/users/twi18192/conda-envs/httomo-install-test/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
      main()
    File "/dls/science/users/twi18192/conda-envs/httomo-install-test/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/dls/science/users/twi18192/conda-envs/httomo-install-test/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
    File "/tmp/pip-build-env-xvzdbfa5/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 410, in build_wheel
      return self._build_with_temp_dir(
    File "/tmp/pip-build-env-xvzdbfa5/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 395, in _build_with_temp_dir
      self.run_setup()
    File "/tmp/pip-build-env-xvzdbfa5/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 311, in run_setup
      exec(code, locals())
    File "<string>", line 51, in <module>
    File "/tmp/pip-build-env-xvzdbfa5/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 103, in setup
      return distutils.core.setup(**attrs)
    File "/tmp/pip-build-env-xvzdbfa5/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 184, in setup
      return run_commands(dist)
    File "/tmp/pip-build-env-xvzdbfa5/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
      dist.run_commands()
    File "/tmp/pip-build-env-xvzdbfa5/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
      self.run_command(cmd)
    File "/tmp/pip-build-env-xvzdbfa5/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 968, in run_command
      super().run_command(command)
    File "/tmp/pip-build-env-xvzdbfa5/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-env-xvzdbfa5/overlay/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 368, in run
      self.run_command("build")
    File "/tmp/pip-build-env-xvzdbfa5/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
      self.distribution.run_command(command)
    File "/tmp/pip-build-env-xvzdbfa5/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 968, in run_command
      super().run_command(command)
    File "/tmp/pip-build-env-xvzdbfa5/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-env-xvzdbfa5/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 132, in run
      self.run_command(cmd_name)
    File "/tmp/pip-build-env-xvzdbfa5/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
      self.distribution.run_command(command)
    File "/tmp/pip-build-env-xvzdbfa5/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 968, in run_command
      super().run_command(command)
    File "/tmp/pip-build-env-xvzdbfa5/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
      cmd_obj.run()
    File "<string>", line 41, in run
    File "/dls/science/users/twi18192/httomo/scripts/yaml_templates_generator.py", line 63, in yaml_generator
      imported_module = importlib.import_module(str(module_name))
    File "/dls/science/users/twi18192/conda-envs/httomo-install-test/lib/python3.10/importlib/__init__.py", line 126, in import_module
      return _bootstrap._gcd_import(name[level:], package, level)
    File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
    File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
    File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
    File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
    File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
    File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
    File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
    File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
    File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
  ModuleNotFoundError: No module named 'httomolib'
  [end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.
ERROR: Failed building wheel for httomo
Failed to build httomo
ERROR: Could not build wheels for httomo, which is required to install pyproject.toml-based projects
```

**Comment by dkazanc** [comment]
Thanks @yousefmoazzam . "The backends aren't installed in the build environment that pip creates" - is this pip virtual environment different from the conda environment where backends should be present?

**Comment by yousefmoazzam** [comment]
Yep, it's an env which `pip` creates during `pip install`, and is separate from any conda env. Its depedencies are listed in the `pyproject.toml` file: https://github.com/DiamondLightSource/httomo/blob/38f3ac81ef01126243cccfe7c763ceb0cf71d72c/pyproject.toml#L2

Notice how I added `pyyaml` in order to get the execution of `yaml_templeates_generator.py` to do `import yaml` correctly, but then imports of the backends in `yaml_templates_generator.py`fail.

**Comment by yousefmoazzam** [comment]
The need to have the backend packages installed in order to generate the YAML templates is an issue for the installation process that will need some thinking. It's the same issue as with the docs build CI needing to generate the YAML templates I guess.

However, in the docs build CI one could at least rely on the fact that a conda env is being used, so the backends like httomolib/httomolibgpu could be installed from the conda channel, and then the imports of `httomolib` and `httomolibgu` work when `yaml_templates_generator.py` is executed.

In this case, the dependencies for the "build env" that `pip install` creates are ones that come from PyPI, not from conda channels. Ie, in order to achieve in the installation process what was done in the docs build CI to get around this issue, we'd need to have `httomolib` and `httomolibgpu` distributed to PyPI or something.

**Comment by yousefmoazzam** [comment]
Given the fact that we only care about function signatures/type information, with some slightly out of the box thinking, I did realise that we could possibly generate "stub files" for the methods. Then get function signature information from the stub files rather than from the python source files, which would avoid needing to do `import` on the backend packages.

However, this is getting pretty complex now, so I think a revaluation of the situation is needed at this point.

References:
- mypy generated stub files: https://mypy.readthedocs.io/en/stable/stubgen.html
- pyright generated stub files: https://github.com/microsoft/pyright/blob/main/docs/type-stubs.md

**Comment by dkazanc** [comment]
Thanks, it is indeed a bit of a problem. Even if we'll be able to distribute our libraries through PyPy , TomoPy is a [problem](https://tomopy.readthedocs.io/en/latest/faq.html#why-can-t-i-install-tomopy-from-pypi-using-pip) then. Let think more...
