### ISSUE TITLE
Nonexistent method in pipeline YAML causes YAML checker to fail unexpectedly

### ISSUE THREAD

**Issue by yousefmoazzam** [DiamondLightSource/httomo#331]
Suppose the following pipeline YAML file is given to the YAML checker (this is a minimal example that reproduces the issue):
```yaml
- method: standard_tomo
  module_path: httomo.data.hdf.loaders
  parameters:
    name: tomo
    data_path: entry1/tomo_entry/data/data
    image_key_path: entry1/tomo_entry/instrument/detector/image_key
    rotation_angles:
      data_path: /entry1/tomo_entry/data/rotation_angle
    dimension: 1
    pad: 0
- method: find_center_vol
  module_path: httomolibgpu.recon.rotation
  parameters:
    ind: mid
    smin: -50
    smax: 50
    srad: 6.0
    step: 0.25
    ratio: 0.5
    drop: 20
```

and notice the incorrect method name `find_center_vol` (should be `find_center_vo`).

The YAML checker correctly reports this as being something incorrect in the YAML. However, afterwards, the YAML checker then fails abruptly:
```
Checking that the YAML_CONFIG is properly indented and has valid mappings and tags...
Sanity check of the YAML_CONFIG was successfully done...

Checking that the first method in the pipeline is a loader...
Loader check successful!!

'httomolibgpu.recon.rotation/find_center_vol' is not a valid method. Please recheck the yaml file.
Traceback (most recent call last):
  File "/dls/science/users/twi18192/conda-envs/httomo/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/dls/science/users/twi18192/conda-envs/httomo/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/dls/science/users/twi18192/httomo/httomo/__main__.py", line 4, in <module>
    main()
  File "/dls/science/users/twi18192/conda-envs/httomo/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/dls/science/users/twi18192/conda-envs/httomo/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/dls/science/users/twi18192/conda-envs/httomo/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/dls/science/users/twi18192/conda-envs/httomo/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/dls/science/users/twi18192/conda-envs/httomo/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/dls/science/users/twi18192/httomo/httomo/cli.py", line 46, in check
    return validate_yaml_config(yaml_config, in_data)
  File "/dls/science/users/twi18192/httomo/httomo/yaml_checker.py", line 403, in validate_yaml_config
    are_param_names_known = check_parameter_names_are_known(conf)
  File "/dls/science/users/twi18192/httomo/httomo/yaml_checker.py", line 171, in check_parameter_names_are_known
    template_yaml_conf = _get_template_yaml_conf(conf)
  File "/dls/science/users/twi18192/httomo/httomo/yaml_checker.py", line 327, in _get_template_yaml_conf
    tmp_conf = yaml_loader(f)
  File "/dls/science/users/twi18192/httomo/httomo/ui_layer.py", line 280, in yaml_loader
    with open(file_path, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/dls/science/users/twi18192/httomo/yaml_templates/httomolibgpu/httomolibgpu.recon.rotation/find_center_vol.yaml'
```

The YAML checker runs _all_ checks, even if some fail, in order to be able to report as many issues in one go, to avoid the user having to constantly re-run the checker each time they fix one error.

The checks are the following: https://github.com/DiamondLightSource/httomo/blob/5ee850af2296f0c285681850035a7554a7347c14/httomo/yaml_checker.py#L396-L409

If a method is found to _not exist_ via the check `check_methods_exist_in_templates()` (ie, `do_methods_exist` gets assigned to `False`), the next check of if the parameter names in the method's config are known still runs.

Meaning, if a nonexistent method is in the pipeline (such as `find_center_vol`), then the YAML checker will carry on after reporting that the method doesn't exist, and attempt to open a YAML template file associated with the nonexistent method. This then obviously fails because a nonexistent method won't have a YAML template. This explains the `FileNotFoundError` at the end of the stacktrace:
```
FileNotFoundError: [Errno 2] No such file or directory: '/dls/science/users/twi18192/httomo/yaml_templates/httomolibgpu/httomolibgpu.recon.rotation/find_center_vol.yaml'
```

**Comment by yousefmoazzam** [comment]
One possible solution to this would be to have a bit more nuance in the checks that the YAML checker runs. For example:
- if a method in the YAML doesn't exist
- _don't_ run the check for if the parameter names are known
- report the fact to the user that this check couldn't be performed for that particular method
- and carry on with all other checks

**Comment by dkazanc** [comment]
thanks Yousef, a valid point. I think that if `method in the YAML doesn't exist ` then nothing should be tested for its parameters, i.e. including:
```
 are_param_names_known = check_parameter_names_are_known(conf) 
 are_param_names_type_str = check_parameter_names_are_str(conf) 
 id_and_side_out_present = check_id_has_side_out(conf) 
 are_ref_ids_valid = check_ref_id_valid(conf) 
 side_out_matches_ref_arg = check_side_out_matches_ref_arg(conf) 
are_required_parameters_missing = check_no_required_parameter_values(conf) 
```
The message indeed needed saying something that _the method blabla doesn't exist and all check for its parameters will be skipped. _
So we only need to check  for  `required_keys_present = check_keys(conf)`  after all, which is actually should be moved right after the loader?

**Comment by yousefmoazzam** [comment]
Yeah, I think it's sensible to move
```python
required_keys_present = check_keys(conf)
```

to be after the loader and before the `check_methods_exist_in_templates()` check.

There's a logical order to do these checks in (check loader, then check the method exists, then if the method exists, check all its parameters), which we hadn't fully thought through until we saw this issue.

It may take a bit of fiddling to do this nicely (for example, if the method doesn't exist, do we set all other checks to have a default of `True` but don't run the checks, or do something else?), but I'm sure it can be done somehow :slightly_smiling_face:
